language: node_js
dist: trusty
sudo: required

# Test envs will overwrite defaults
env:
  - ETHWS=wss://kovan.infura.io/ws

node_js:
  - "node"

cache:
  directories:
    - build/src/node_modules
install:
  # This is a dockerized application, the node app is in /build/src
  - cd ./build/src
  - npm install
before_script:
  - npm run lint
script:
  - npm test -- --coverage # Include coverage when running tests
after_success: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls